<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SectorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $wcli_crm_sectors_olds  = array(
            array(
                "id" => 1,
                "name" => "Industrie",
                "slug" => "industrie",
                "contenu" => "[]",
                "txt_intro" => NULL,
                "txt_kpi" => "J'ai déjà travaillé de nombreuses fois pour l'industrie.",
                "parent_id" => 18,
                "nest_left" => 4,
                "nest_right" => 17,
                "nest_depth" => 1,
                "created_at" => "2020-02-22 12:30:51",
                "updated_at" => "2022-11-03 17:02:32",
            ),
            array(
                "id" => 2,
                "name" => "Industrie Agro Alimentaire",
                "slug" => "i-aa",
                "contenu" => "[]",
                "txt_intro" => NULL,
                "txt_kpi" => NULL,
                "parent_id" => 1,
                "nest_left" => 9,
                "nest_right" => 14,
                "nest_depth" => 2,
                "created_at" => "2020-02-22 12:30:51",
                "updated_at" => "2022-11-03 17:02:32",
            ),
            array(
                "id" => 3,
                "name" => "Grand compte (i-aa)",
                "slug" => "i-aa-grdc",
                "contenu" => "[]",
                "txt_intro" => NULL,
                "txt_kpi" => NULL,
                "parent_id" => 2,
                "nest_left" => 10,
                "nest_right" => 11,
                "nest_depth" => 3,
                "created_at" => "2020-02-22 12:30:51",
                "updated_at" => "2022-11-03 17:02:32",
            ),
            array(
                "id" => 4,
                "name" => "PME (i-aa)",
                "slug" => "i-aa-pme",
                "contenu" => "[]",
                "txt_intro" => NULL,
                "txt_kpi" => NULL,
                "parent_id" => 2,
                "nest_left" => 12,
                "nest_right" => 13,
                "nest_depth" => 3,
                "created_at" => "2020-02-22 12:30:51",
                "updated_at" => "2022-11-03 17:02:32",
            ),
            array(
                "id" => 5,
                "name" => "Industrie lourde",
                "slug" => "i-lourde",
                "contenu" => "[{\"code\":\"intro\",\"text\":\"Ceci est un texte d'intro.\",\"text_html\":\"<p>Ceci est un texte d'intro en <strong>HTML<\\/strong><\\/p>\\r\\n\\r\\n<p><strong><em>Il permet de faire plus de chose.&nbsp;<\\/em><\\/strong><\\/p>\\r\\n\"},{\"code\":\"kpi\",\"text\":\"Ici on traite des facteurs cl\\u00e9 de succ\\u00e8s !\",\"text_html\":\"<blockquote>\\r\\n\\r\\n\\t<p>Ici on traite des facteurs cl\\u00e9 de succ\\u00e8s !<\\/p>\\r\\n<\\/blockquote>\\r\\n\"}]",
                "txt_intro" => NULL,
                "txt_kpi" => NULL,
                "parent_id" => 1,
                "nest_left" => 15,
                "nest_right" => 16,
                "nest_depth" => 2,
                "created_at" => "2020-02-22 12:30:51",
                "updated_at" => "2022-11-03 17:02:32",
            ),
            array(
                "id" => 6,
                "name" => "ingénierie",
                "slug" => "i-ingenierie",
                "contenu" => "[{\"code\":\"intro\",\"text\":\"Ceci est un texte d'intro.\",\"text_html\":\"<p>Ceci est un texte d'intro en <strong>HTML<\\/strong><\\/p>\\r\\n\\r\\n<p><strong><em>Il permet de faire plus de chose.&nbsp;<\\/em><\\/strong><\\/p>\\r\\n\"},{\"code\":\"kpi\",\"text\":\"Ici on traite des facteurs cl\\u00e9 de succ\\u00e8s !\",\"text_html\":\"<blockquote>\\r\\n\\r\\n\\t<p>Ici on traite des facteurs cl\\u00e9 de succ\\u00e8s !<\\/p>\\r\\n<\\/blockquote>\\r\\n\"}]",
                "txt_intro" => NULL,
                "txt_kpi" => "Mes applications et sites répondent aux process et aux problématiques de l'ingénierie",
                "parent_id" => 1,
                "nest_left" => 7,
                "nest_right" => 8,
                "nest_depth" => 2,
                "created_at" => "2020-02-22 12:30:51",
                "updated_at" => "2022-11-03 17:02:32",
            ),
            array(
                "id" => 7,
                "name" => "Immobilier",
                "slug" => "immobilier",
                "contenu" => "[{\"code\":\"intro\",\"text\":\"Ceci est un texte d'intro.\",\"text_html\":\"<p>Ceci est un texte d'intro en <strong>HTML<\\/strong><\\/p>\\r\\n\\r\\n<p><strong><em>Il permet de faire plus de chose.&nbsp;<\\/em><\\/strong><\\/p>\\r\\n\"},{\"code\":\"kpi\",\"text\":\"Ici on traite des facteurs cl\\u00e9 de succ\\u00e8s !\",\"text_html\":\"<blockquote>\\r\\n\\r\\n\\t<p>Ici on traite des facteurs cl\\u00e9 de succ\\u00e8s !<\\/p>\\r\\n<\\/blockquote>\\r\\n\"}]",
                "txt_intro" => NULL,
                "txt_kpi" => "Mes applications et sites répondent aux besoins des sociétés opérants dans le secteur immobilier",
                "parent_id" => 18,
                "nest_left" => 38,
                "nest_right" => 39,
                "nest_depth" => 1,
                "created_at" => "2020-02-22 12:30:51",
                "updated_at" => "2024-08-23 14:57:33",
            ),
            array(
                "id" => 8,
                "name" => "Pharmaceutique",
                "slug" => "pharma",
                "contenu" => "[{\"code\":\"intro\",\"text\":\"Ceci est un texte d'intro.\",\"text_html\":\"<p>Ceci est un texte d'intro en <strong>HTML<\\/strong><\\/p>\\r\\n\\r\\n<p><strong><em>Il permet de faire plus de chose.&nbsp;<\\/em><\\/strong><\\/p>\\r\\n\"},{\"code\":\"kpi\",\"text\":\"Ici on traite des facteurs cl\\u00e9 de succ\\u00e8s !\",\"text_html\":\"<blockquote>\\r\\n\\r\\n\\t<p>Ici on traite des facteurs cl\\u00e9 de succ\\u00e8s !<\\/p>\\r\\n<\\/blockquote>\\r\\n\"}]",
                "txt_intro" => NULL,
                "txt_kpi" => "Mes applications et sites répondent aux process et aux problématiques de l'industrie pharmaceutique",
                "parent_id" => 1,
                "nest_left" => 5,
                "nest_right" => 6,
                "nest_depth" => 2,
                "created_at" => "2020-02-22 12:30:51",
                "updated_at" => "2022-11-03 17:02:32",
            ),
            array(
                "id" => 9,
                "name" => "Conseil & services",
                "slug" => "conseil-services",
                "contenu" => "[]",
                "txt_intro" => NULL,
                "txt_kpi" => "Mes applications et sites répondent aux besoins des sociétés de services et de conseil",
                "parent_id" => 18,
                "nest_left" => 26,
                "nest_right" => 37,
                "nest_depth" => 1,
                "created_at" => "2020-02-22 12:30:51",
                "updated_at" => "2024-08-23 14:57:33",
            ),
            array(
                "id" => 10,
                "name" => "Conseil RH",
                "slug" => "c-rh",
                "contenu" => "[{\"code\":\"intro\",\"text\":\"Ceci est un texte d'intro.\",\"text_html\":\"<p>Ceci est un texte d'intro en <strong>HTML<\\/strong><\\/p>\\r\\n\\r\\n<p><strong><em>Il permet de faire plus de chose.&nbsp;<\\/em><\\/strong><\\/p>\\r\\n\"},{\"code\":\"kpi\",\"text\":\"Ici on traite des facteurs cl\\u00e9 de succ\\u00e8s !\",\"text_html\":\"<blockquote>\\r\\n\\r\\n\\t<p>Ici on traite des facteurs cl\\u00e9 de succ\\u00e8s !<\\/p>\\r\\n<\\/blockquote>\\r\\n\"}]",
                "txt_intro" => NULL,
                "txt_kpi" => NULL,
                "parent_id" => 9,
                "nest_left" => 29,
                "nest_right" => 30,
                "nest_depth" => 2,
                "created_at" => "2020-02-22 12:30:51",
                "updated_at" => "2024-08-23 14:57:33",
            ),
            array(
                "id" => 11,
                "name" => "Conseil Finance",
                "slug" => "c-finance",
                "contenu" => "[{\"code\":\"intro\",\"text\":\"Ceci est un texte d'intro.\",\"text_html\":\"<p>Ceci est un texte d'intro en <strong>HTML<\\/strong><\\/p>\\r\\n\\r\\n<p><strong><em>Il permet de faire plus de chose.&nbsp;<\\/em><\\/strong><\\/p>\\r\\n\"},{\"code\":\"kpi\",\"text\":\"Ici on traite des facteurs cl\\u00e9 de succ\\u00e8s !\",\"text_html\":\"<blockquote>\\r\\n\\r\\n\\t<p>Ici on traite des facteurs cl\\u00e9 de succ\\u00e8s !<\\/p>\\r\\n<\\/blockquote>\\r\\n\"}]",
                "txt_intro" => NULL,
                "txt_kpi" => NULL,
                "parent_id" => 9,
                "nest_left" => 31,
                "nest_right" => 32,
                "nest_depth" => 2,
                "created_at" => "2020-02-22 12:30:51",
                "updated_at" => "2024-08-23 14:57:33",
            ),
            array(
                "id" => 12,
                "name" => "SI",
                "slug" => "c-si",
                "contenu" => "[{\"code\":\"intro\",\"text\":\"Ceci est un texte d'intro.\",\"text_html\":\"<p>Ceci est un texte d'intro en <strong>HTML<\\/strong><\\/p>\\r\\n\\r\\n<p><strong><em>Il permet de faire plus de chose.&nbsp;<\\/em><\\/strong><\\/p>\\r\\n\"},{\"code\":\"kpi\",\"text\":\"Ici on traite des facteurs cl\\u00e9 de succ\\u00e8s !\",\"text_html\":\"<blockquote>\\r\\n\\r\\n\\t<p>Ici on traite des facteurs cl\\u00e9 de succ\\u00e8s !<\\/p>\\r\\n<\\/blockquote>\\r\\n\"}]",
                "txt_intro" => "Je crée des portails de services et des sites web capables d’interagir avec vos données et de les mettre en scène (3D, Word, PDF, email)  pour vous ou vos clients",
                "txt_kpi" => NULL,
                "parent_id" => 9,
                "nest_left" => 35,
                "nest_right" => 36,
                "nest_depth" => 2,
                "created_at" => "2020-02-22 12:30:52",
                "updated_at" => "2024-08-23 14:57:33",
            ),
            array(
                "id" => 13,
                "name" => "Secteur public",
                "slug" => "secteur-public",
                "contenu" => "[{\"code\":\"intro\",\"text\":\"Ceci est un texte d'intro.\",\"text_html\":\"<p>Ceci est un texte d'intro en <strong>HTML<\\/strong><\\/p>\\r\\n\\r\\n<p><strong><em>Il permet de faire plus de chose.&nbsp;<\\/em><\\/strong><\\/p>\\r\\n\"},{\"code\":\"kpi\",\"text\":\"Ici on traite des facteurs cl\\u00e9 de succ\\u00e8s !\",\"text_html\":\"<blockquote>\\r\\n\\r\\n\\t<p>Ici on traite des facteurs cl\\u00e9 de succ\\u00e8s !<\\/p>\\r\\n<\\/blockquote>\\r\\n\"}]",
                "txt_intro" => NULL,
                "txt_kpi" => "Mes applications et sites répondent aux process et aux problématiques du secteur public",
                "parent_id" => 18,
                "nest_left" => 18,
                "nest_right" => 25,
                "nest_depth" => 1,
                "created_at" => "2020-02-22 12:30:52",
                "updated_at" => "2024-08-23 14:57:33",
            ),
            array(
                "id" => 14,
                "name" => "Collectivité",
                "slug" => "sp-collectivite",
                "contenu" => "[{\"code\":\"intro\",\"text\":\"Ceci est un texte d'intro.\",\"text_html\":\"<p>Ceci est un texte d'intro en <strong>HTML<\\/strong><\\/p>\\r\\n\\r\\n<p><strong><em>Il permet de faire plus de chose.&nbsp;<\\/em><\\/strong><\\/p>\\r\\n\"},{\"code\":\"kpi\",\"text\":\"Ici on traite des facteurs cl\\u00e9 de succ\\u00e8s !\",\"text_html\":\"<blockquote>\\r\\n\\r\\n\\t<p>Ici on traite des facteurs cl\\u00e9 de succ\\u00e8s !<\\/p>\\r\\n<\\/blockquote>\\r\\n\"}]",
                "txt_intro" => NULL,
                "txt_kpi" => NULL,
                "parent_id" => 13,
                "nest_left" => 21,
                "nest_right" => 22,
                "nest_depth" => 2,
                "created_at" => "2020-02-22 12:30:52",
                "updated_at" => "2024-08-23 14:57:33",
            ),
            array(
                "id" => 15,
                "name" => "Entreprise Publique",
                "slug" => "sp-ent-public",
                "contenu" => "[{\"code\":\"intro\",\"text\":\"Ceci est un texte d'intro.\",\"text_html\":\"<p>Ceci est un texte d'intro en <strong>HTML<\\/strong><\\/p>\\r\\n\\r\\n<p><strong><em>Il permet de faire plus de chose.&nbsp;<\\/em><\\/strong><\\/p>\\r\\n\"},{\"code\":\"kpi\",\"text\":\"Ici on traite des facteurs cl\\u00e9 de succ\\u00e8s !\",\"text_html\":\"<blockquote>\\r\\n\\r\\n\\t<p>Ici on traite des facteurs cl\\u00e9 de succ\\u00e8s !<\\/p>\\r\\n<\\/blockquote>\\r\\n\"}]",
                "txt_intro" => NULL,
                "txt_kpi" => NULL,
                "parent_id" => 13,
                "nest_left" => 23,
                "nest_right" => 24,
                "nest_depth" => 2,
                "created_at" => "2020-02-22 12:30:52",
                "updated_at" => "2024-08-23 14:57:33",
            ),
            array(
                "id" => 16,
                "name" => "Agences",
                "slug" => "c-ag",
                "contenu" => "[{\"code\":\"intro\",\"text\":\"Ceci est un texte d'intro.\",\"text_html\":\"<p>Ceci est un texte d'intro en <strong>HTML<\\/strong><\\/p>\\r\\n\\r\\n<p><strong><em>Il permet de faire plus de chose.&nbsp;<\\/em><\\/strong><\\/p>\\r\\n\"},{\"code\":\"kpi\",\"text\":\"Ici on traite des facteurs cl\\u00e9 de succ\\u00e8s !\",\"text_html\":\"<blockquote>\\r\\n\\r\\n\\t<p>Ici on traite des facteurs cl\\u00e9 de succ\\u00e8s !<\\/p>\\r\\n<\\/blockquote>\\r\\n\"}]",
                "txt_intro" => "Je crée des portails de services et des sites web capables d’interagir avec vos données et de les mettre en scène (3D, Word, PDF, email)  pour vous ou vos clients",
                "txt_kpi" => "Montage photo automatique, 3d, Mailing, conception de PDF, Word et PPT, mes applications répondent aux besoins des Agences.",
                "parent_id" => 9,
                "nest_left" => 27,
                "nest_right" => 28,
                "nest_depth" => 2,
                "created_at" => "2020-02-22 12:30:52",
                "updated_at" => "2024-08-23 14:57:33",
            ),
            array(
                "id" => 17,
                "name" => "Livraison",
                "slug" => "s-livraison",
                "contenu" => "[{\"code\":\"intro\",\"text\":\"Ceci est un texte d'intro.\",\"text_html\":\"<p>Ceci est un texte d'intro en <strong>HTML<\\/strong><\\/p>\\r\\n\\r\\n<p><strong><em>Il permet de faire plus de chose.&nbsp;<\\/em><\\/strong><\\/p>\\r\\n\"},{\"code\":\"kpi\",\"text\":\"Ici on traite des facteurs cl\\u00e9 de succ\\u00e8s !\",\"text_html\":\"<blockquote>\\r\\n\\r\\n\\t<p>Ici on traite des facteurs cl\\u00e9 de succ\\u00e8s !<\\/p>\\r\\n<\\/blockquote>\\r\\n\"}]",
                "txt_intro" => NULL,
                "txt_kpi" => NULL,
                "parent_id" => 9,
                "nest_left" => 33,
                "nest_right" => 34,
                "nest_depth" => 2,
                "created_at" => "2020-02-22 12:30:52",
                "updated_at" => "2024-08-23 14:57:33",
            ),
            array(
                "id" => 18,
                "name" => "tout secteur",
                "slug" => "base",
                "contenu" => "[]",
                "txt_intro" => "Je crée des portails de services et des sites web capables d’interagir avec vos données et de les mettre en scène : 3D, Word, PDF, email…",
                "txt_kpi" => "J'ai une longue expérience dans divers secteurs et particulièrement dans le **BToB**",
                "parent_id" => NULL,
                "nest_left" => 1,
                "nest_right" => 42,
                "nest_depth" => 0,
                "created_at" => "2020-09-02 12:32:29",
                "updated_at" => "2024-08-23 14:57:33",
            ),
            array(
                "id" => 19,
                "name" => "Banque / Assurance",
                "slug" => "banque-assurance",
                "contenu" => "",
                "txt_intro" => NULL,
                "txt_kpi" => NULL,
                "parent_id" => 18,
                "nest_left" => 40,
                "nest_right" => 41,
                "nest_depth" => 1,
                "created_at" => "2022-10-12 14:15:59",
                "updated_at" => "2024-08-23 14:57:33",
            ),
            array(
                "id" => 20,
                "name" => "Associatif",
                "slug" => "associatif",
                "contenu" => "",
                "txt_intro" => "",
                "txt_kpi" => "Mes applications et sites répondent aux process et aux problématiques du milieu associatif",
                "parent_id" => 18,
                "nest_left" => 2,
                "nest_right" => 3,
                "nest_depth" => 1,
                "created_at" => "2022-11-03 16:52:59",
                "updated_at" => "2022-11-03 17:02:32",
            ),
            array(
                "id" => 21,
                "name" => "EPCI",
                "slug" => "epci",
                "contenu" => "",
                "txt_intro" => NULL,
                "txt_kpi" => NULL,
                "parent_id" => 13,
                "nest_left" => 19,
                "nest_right" => 20,
                "nest_depth" => 2,
                "created_at" => "2024-08-23 14:57:21",
                "updated_at" => "2024-08-23 14:57:33",
            ),
        );

        $newSector = $this->updateDataForFilament($wcli_crm_sectors_olds);
        DB::table('crm_sectors')->insert($newSector);
    }

    /**
     * Update data for Filament.
     */
    public function updateDataForFilament(array $sectors): array
    {
        return array_map(function ($sector) {
            // Supprimer les champs nest_left, nest_right, nest_depth
            unset($sector['nest_left'], $sector['nest_right'], $sector['nest_depth']);

            // Remplacer le champ name par title
            $sector['title'] = $sector['name'];
            unset($sector['name']);
            if($sector['parent_id'] == NULL) {
                $sector['parent_id'] = -1 ;
            }

            return $sector;
        }, $sectors);
    }
}
